---
- hosts: localhost
  user: ubuntu
  become_method: sudo
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
  roles:
    - ec2_creation
    - refresh

- hosts: tag_Name_{{ec2_config.instance_tag_name}} 
  become_method: sudo
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

- hosts: tag_Name_{{ec2_config.instance_tag_name}}
  become_method: sudo
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.java
      become: yes 

- hosts: tag_Name_{{ec2_config.instance_tag_name}} 
  become_method: sudo
  remote_user: root 
  gather_facts: true
#  pre_tasks:
#    - include_vars: plugins.yml
  vars_files:
    - vars/main.yml
    - vars/plugins.yml
  roles:
    - { role: geerlingguy.jenkins, jenkins_plugins: "{{ plugins }}" } 

    
