---
- name: Creating EC2 Instance
  ec2:
    region: "{{ec2_config.region}}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    zone: "{{ec2_config.zone}}"
    keypair: "{{ec2_config.keypair}}"
    instance_type: "{{ec2_config.instance_type}}"
    image: "{{ec2_config.image}}"
#    vpc_subnet_id: "{{ec2_config.vpc_subnet_id}}"
    group: "{{ec2_config.group}}"
#    assign_public_ip: "{{ec2_config.assign_public_ip}}"
    count: 1
    wait: yes
    instance_tags:
       Name: "{{ec2_config.instance_tag_name}}"
  register: ec2

- name: Waiting for Instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2.instances[0].public_dns_name  }}"
    port: 22
    timeout: 320

- name: copy key to hosts
  shell: scp /root/.ssh/authorized_keys ubuntu@{{ item.public_ip }}:/home/ubuntu/.ssh/authorized_keys
  with_items:
   - "{{ ec2.instances }}"

- name: copy key to host root
  shell: ssh ubuntu@{{ item.public_ip }} 'sudo cp /home/ubuntu/.ssh/authorized_keys /root/.ssh/'
  with_items:
   - "{{ ec2.instances }}"

- name: Add new instance to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ec2_config.instance_tag_name}}" 
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_user: ubuntu
    ansible_ssh_host: "{{ item.public_ip }}"
  with_items:
   - "{{ ec2.instances }}"

#- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
#  local_action: lineinfile
#                dest="/etc/ansible/hosts"
#                regexp={{ item.public_ip }}
#                insertafter="[webservers]" line={{ item.public_ip }}
#  with_items:
#    - "{{ ec2.instances }}" 

